version: "3"

services:
    website:
        image: node:14-alpine3.13
        working_dir: /app
        volumes:
            - /app/node_modules
            - ./:/app
        environment:
            - VITE_API_URL=http://api.voconsteroid.com:50000/
        ports:
            - 8080:3000
            - 6006:6006
            - 24678:24678
        stdin_open: true
